#!/bin/bash

isMicOn="$(amixer get 'Capture',0 | grep '\[on\]')"
#if [amixer get 'Capture',0 | grep "\[on\]"]
if [ "$isMicOn" ];
then
	twmnc -c "Mic On" --fg red -d 500 -s 25 --fs 16
else
	twmnc -c "Mic Off" --fg red -d 500 -s 25 --fs 16
fi
