#!/bin/bash

my_time=0.4

com_1="vim"
com_2=":"
com_3=":"
com_4="ranger"
com_5="ranger"

xterm -e "cd $1; $com_1; bash" &
sleep $my_time
xterm -e "cd $1; $com_2; bash" &
sleep $my_time
xterm -e "cd $1; $com_3; bash" &
sleep $my_time
xterm -e "cd $1; $com_4; bash" &
sleep $my_time
xterm -e "cd $1; $com_5; bash" &
