#!/bin/bash

my_time=0.5

com_1=":"
com_2=":"
com_3=":"
com_4=":"
com_5=":"
com_6=":"
com_7=":"
com_8=":"

xterm -e "cd $1; $com_1; bash" &
sleep $my_time
xterm -e "cd $1; $com_2; bash" &
sleep $my_time
xterm -e "cd $1; $com_3; bash" &
sleep $my_time
xterm -e "cd $1; $com_4; bash" &
sleep $my_time
xterm -e "cd $1; $com_5; bash" &
sleep $my_time
xterm -e "cd $1; $com_6; bash" &
sleep $my_time
xterm -e "cd $1; $com_7; bash" &
sleep $my_time
xterm -e "cd $1; $com_8; bash" &
