#!/bin/bash

speakerVolume="$([[ "$(amixer get 'Master')" =~ ([0-9]*%) ]] && echo "${BASH_REMATCH[1]}")"
dunstify -r 1 -t 1000 "Volume: $speakerVolume" -h string:bgcolor:#000000 -h string:fgcolor:#ffffff 
