#!/bin/bash

speakerVolume="$([[ "$(amixer get 'Master')" =~ ([0-9]*%) ]] && echo "${BASH_REMATCH[1]}")"
path=/tmp/last-speaker-volume
last=$(<$path)

if [ "$speakerVolume" = "0%" ]; then
    amixer -c 0 sset Master $last && speakers-notify
else
    echo $speakerVolume > $path
    amixer -c 0 sset Master 0% && speakers-notify
fi
