#!/bin/bash

i3-msg "workspace 2; append_layout /home/archie/.config/i3/workspace-emacs-2.json"

my_time=0.1

com_1="ranger"
com_2=":"
com_3=":"
com_4=":"

emacs $1 &
xterm -e "cd $1; $com_1 $1 $1; bash" &
sleep $my_time
xterm -e "cd $1; $com_2; bash" &
sleep $my_time
xterm -e "cd $1; $com_3; bash" &
sleep $my_time
xterm -e "cd $1; $com_4; bash" &
