#!/bin/bash

path=/sys/class/backlight/intel_backlight
current=$(<$path/brightness)
max=$(<$path/max_brightness)
step=$((max/100*15))
new=$((current-step))

if [ "$new" -ge 0 ]; then
    tee $path/brightness <<< $new
    brightness-notify
else
    brightness-notify
fi
