#!/bin/bash

value=$(</sys/class/backlight/intel_backlight/brightness)
max_value=$(</sys/class/backlight/intel_backlight/max_brightness)
percent=$((value*100/max_value))
dunstify -r 1 -t 1000 "Brightness: %$percent" -h string:bgcolor:#444400 -h string:fgcolor:#ffff00 
# dunstify -r 1 -t 1000 "Brightness: %$percent" -h string:bgcolor:#000000 -h string:fgcolor:#ffffff 
