#!/bin/bash

value=$(</sys/class/backlight/intel_backlight/brightness)
max_value=$(</sys/class/backlight/intel_backlight/max_brightness)
percent=$((value*100/max_value))

notify-send -t 500 "Brightness: %$percent" -h string:bgcolor:#444400 -h string:fgcolor:#ffff00 
