#!/bin/bash

sleep $(($1 * 60))

if [[ $1 -eq 1 ]]; then
    dunstify -t 0 "TIMER EXPIRED" "$1 minute passed!" -h string:bgcolor:#ff0000
else
    dunstify -t 0 "TIMER EXPIRED" "$1 minutes passed!" -h string:bgcolor:#ff0000
fi