#!/bin/bash

speakerVolume="$([[ "$(amixer get 'Master')" =~ ([0-9]*%) ]] && echo "${BASH_REMATCH[1]}")"
notify-send -t 500 "Volume: $speakerVolume" -h string:bgcolor:#000000 -h string:fgcolor:#ffffff 
